language: cpp
sudo: required
dist: trusty
notifications:
  email:
  - jmirabel@laas.fr
branches:
  only:
  - master
  - devel
compiler:
- gcc
before_install:
- git submodule update --init --recursive
- sudo apt-get update -qq
- sudo apt-get install -qq doxygen doxygen-latex libboost-all-dev libtinyxml-dev
script: ./.travis/build
